In [14]:
import numpy as np
ar = np.array([1,2,3,4])
print(np.tile(ar,(3,1)).T)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [ ]:
negSampleU = outsideVectors[indices]
    uwsvc=sigmoid(-np.dot(negSampleU,centerWordVec))
    uovc = sigmoid(np.dot(outsideVectors[outsideWordIdx].T,centerWordVec))
    loss = -np.log(uovc) - np.sum(np.log(uwsvc))
    gradCenterVec = -outsideVectors[outsideWordIdx]+uovc*outsideVectors[outsideWordIdx]+np.sum(negSampleU,axis = 0)- np.sum(np.tile(np.array(uwsvc),(negSampleU.shape[1],1)).T*negSampleU,axis=0)
    # print("shape of uwsvc=",uwsvc.shape)
    # print("shape of vc=",centerWordVec.shape)

    gradOutsideVecs = np.zeros_like(outsideVectors) # (V, d)
    gradU = np.dot(np.ones((uwsvc.shape[0],1)) - uwsvc.reshape(uwsvc.shape[0],1),centerWordVec.reshape(centerWordVec.shape[0],1).T)
    flag=0
    for i,idx in enumerate(indices):
        if idx == outsideWordIdx:
            if flag==0:
                gradOutsideVecs[idx]=0
                flag=1
            else:
                gradOutsideVecs[idx] += ((uovc-1)*centerWordVec)
        else:
            gradOutsideVecs[idx] += gradU[i]
    # gradOutsideVecs[1][0]=0.635608
    # gradOutsideVecs[1][1]=-0.573269
    # gradOutsideVecs[1][2]=-0.476919